patch: edit document name inline (#244)

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -1,10 +1,11 @@
 #!/bin/bash
 
 npx lint-staged
+npm run test:unit -- run --silent
 
 if [ $? -ne 0 ]; then
-    echo "Pre-commit hook failed. Aborting the commit."
-    exit 1
+  echo "Pre-commit hook failed. Aborting the commit."
+  exit 1
 fi
 
 exit 0
